package jp.ac.osaka.u.ist.t_ishizu.TestHeuristicICCA;

public class TokenKind {
	public static final int RESERVED = 0;
	public static final int NON_RESERVED = 1;
	public static final int COMMA = 2;
	public static final int SEMICOLON = 3;
	public static final int L_PALEN = 4;
	public static final int R_PALEN = 5;
	public static final int L_BRACE = 6;
	public static final int R_BRACE = 7;
	public static final int COMMENT = 8;
	public static final int L_STAR_COMMENT =  9;
	public static final int R_STAR_COMMENT = 10;
	
	public static final String[] reservedWords = new String[]{
		"ABSENCE",
		"ACCEPT","ACCESS","ACTIVE","ACTUAL",
		"ADD","ADDRESS","ADDRESSED","ADVANCING","AFTER","ALIAS","ALL","ALPHABET",
		"ALPHABETIC","ALPHABETIC-LOWER","ALPHABETIC-UPPER",
		"ALPHANUMERIC","ALPHANUMERIC-EDITED","ALSO","ALTER","ALTERNATE",
		"AND","ANY","APPLY","ARE","AREA","AREAS","ARGUMENT","ARITHMETIC","AS",
		"ASCENDING","ASSIGN","ASYNC","AT","ATRIBUTE",
		"AUTHOR","AUTO","AUTO-ADVANCE","AUTO-SHIFT","AUTO-SKIP","AUTOMATIC",
		
		"B-AND","B-EXOR","B-LESS","B-NOT","B-NOT","B-OR","BACK","BACKGROUND-COLOR",
		"BACKGROUND-COLOUR","BACKWARD","BASIS","BEEP","BEFORE","BIGINNING",
		"BELL","BINARY","BIT","BITS","BLACK","BLANK","BLINK","BLOCK","BLUE",
		"BOOLEAN","BOTTOM","BUZZER","BY",
		
		"CO1","CO2","CO3","CO4","CO5","CO6","CO7","CO8","CO9","C10","C11","C12",
		"CALL","CALL-CONVENTION","CANCEL","CBL","CBL-CTR","CD","CF","CH","CHAIN",
		"CHAINING","CHANGED","CHARACTERS","CHARACTERS","CHECK","CLASS","CLASS-CONTROL",
		"CLASS-ID","CLASS-OBJECT","CLOCK-UNITS","CLOSE","COBOL","CODE","CODE-SET",
		"COL","COLLANTING","COLLECTABLE","COLOR","COLUMN","COM-REG","COMMA","COMMAND",
		"COMMIT","COMMON","COMMUNICATION","COMP","COMP-0","COMP-1","COMP-2","COMP-3",
		"COMP-4","COMP-5","COMP-6","COMP-X","COMPUTATIONAL","COMPUTATIONAL-0",
		"COMPUTATIONAL-1","COMPUTATIONAL-2","COMPUTATIONAL-3","COMPUTATIONAL-4",
		"COMPUTATIONAL-5","COMPUTATIONAL-6","COMPUTATIONAL-X","COMPUTE",
		"CONFIGURATION","CONNECT","CONSOLE","CONSTRAINT","CONTAINED","CONTAINS",
		"CONTENT","CONTINUE","CONTROL","CONTROLS","CONVERT","CONVERTING","COPY",
		"CORE-INDEX","CORR","CORRESPONDING","COUNT","CRT","CRT-UNDER","CSP","CSV",
		"CURRENCY","CURRENT","CURRENT-DATE","CURSOR","CYCLE","CYL-INDEX","CYL-OVERFLON",
		
		"DATA","DATE","DATE-COMPILED","DATE-WRITTEN","DAY","DAY-OF-WEEK","DB",
		"DB-ACCESS-CONTROL-KEY","DB-DATA-NAME","DB-EXCEPTION","DB-RECORD-NAME",
		"DB-SET-NAME","DB-STATUS","DBCS","DE","DEBUG","DEBUG-CONTENTS","DEBUG-ITEM",
		"DEBUG-LINE","DEBUG-NAME","DEBUG-SUB-1","DEBUG-SUB-2","DEBUG-SUB-3",
		"DECIMAL-POINT","DECLARATIVES","DEFAULT","DELETE","DELIMITED","DELIMITER",
		"DEPENDING","DEPTH","DESCENDING","DESTINATION","DETAIL","DISABLE","DISCONNECT",
		"DISP","DISPLAY","DISPLAY-ST","DIVIDE","DIVISION","DOUBLE","DOWN","DUPLICATE",
		"DUPLICATES","DYNAMIC",
		
		"ECHO","EGCS","EGI","EJECT","ELSE","EMI","EMPTY","EMPTY-CHECK","ENABLE","END",
		"END-ACCEPT","END-ADD","END-CALL","END-CHAIN","END-COMPUTE","END-DELETE",
		"END-DISPLAY","END-DIVIDE","END-EVALUATE","END-EXEC","END-IF","END-INVOKE",
		"END-MULTIPLY","END-OF-PAGE","END-ON","END-PERFORM","END-READ","END-RECEIVE",
		"END-RETURN","END-REWRITE","END-SERACH","END-START","END-STRING","END-SUBTRACT",
		"END-UNSTRING","END-WRITE","ENDING","ENTER","ENTER-CHECK","ENTRY","ENVIRONMENT",
		"EOL","EOP","EOS","EQL","EQUAL","EQUALS","ERASE","ERASING","ERROR","ESCAPE",
		"ESI","ETI","EVALUATE","EVERY","EXAMINE","EXCEEDS","EXCEPTION","EXCESS-3",
		"EXCLUSIVE","EXEC","EXECUTE","EXHIBIT","EXIT","EXOR","EXTEND","EXTEND-1",
		"EXTEND-2","EXTEND-3","EXTENDED-SEARCH","EXTERNAL","EXTERNAL-PROGRAM",
		
		"FALSE","FD","FETCH","FH-FCD","FH-KEYDEF","FIELD","FILE","FILE-CONTROL",
		"FILE-ID","FILE-LIMIT","FILE-LIMITS","FILE-SHARE","FILES","FILLER","FINAL",
		"FIND","FINISH","FIRST","FIXED","FIXED-SCROLL-LINE","FOOTING","FOR",
		"FOREGROUND-COLOR","FOREGROUND-CLOUR","FORMAT","FORMS-OVERLAY","FREE","FROM",
		"FULL","FUNCTION",
		
		"GENERATE","GET","GINING","GLOBAL","GO","GOBACK","GREATER","GREEN","GRID","GROUP",
		
		"HEADING","HELP","HIGH","HIGH-INTENSITY","HIGH-VALUE","HIGH-VALUES",
		"HIGHLIGHT","HOLD","HOST",
		
		"I-O","I-O-CONTROL","ID","IDENTIFICATION","IF","IGNORE","IN","INCLUDE",
		"INDEX","INDEXED","INDICATE","INHERITS","INITIAL","INITIALIZEINTO",
		"INITIATE","INPUT","INPUT-OUTPUT","INSERT","INSPECT","INSTALLATION",
		"INTER-PUNCH","INTERFACE","INTERFACE-CONTROL","INTERFACE-ID","INTERVAL",
		"INVALID","INVARIANT","INVOKE","IS",
		
		"JAPANESE","JOURNAL","JUST","JUSTIFIED",
		
		"KANJI","KEEP","KEPT","KEY","KEYBOARD",
		
		"LABEL","LABEL-RETURN","LAST","LD","LEADING","LEAVE","LEFT","LEFT-JUSTIFY",
		"LEFTLINE","LENGTH","LENGTH-CHECK","LESS","LETTER","LIBRARY","LIMIT",
		"LIMITS","LIN","LINAGE","LINAGE-COUNTER","LINE","LINE-COUNTER","LINES",
		"LINKAGE","LOCAL-STORAGE","LOCALLY","LOCK","LOCKING","LONG","LOW",
		"LOW-INTENSITY","LOW-VALUE","LOW-VALUES","LOWER","LOWLIGHT",
		
		"MEGENTA","NANUAL","MAP","NAPPING","MASTER-INDEX","MEMBER","MEMORY",
		"MERGE","MESSAGE","METHOD","METHOD-ID","MODE","MODIFY","MODULES",
		"MORE-LABELS","MOVE","MULTIPLE","MULTIPLY",
		
		"NAME","NAMED","NATIONAL","NATIONAL-EDITED","NATIVE","NCHAR",
		"NEGATIVE","NEXT","NO","NO-ECHO","NONE","NORMAL","NOT","NOTE","NSTD-REELS",
		"NULL","NULLIFY","NULLS","NUMBER","NUMERIC","NUMERIC-EDIT","NUMERIC-EDITED",
		
		"OBJECT","OBJECT-COMPUTE","OBJECT-PROGRAM","OCCURS","OF","OFF","OLE",
		"OLE-RETURN","OMITTED","ON","ONLY","OPEN","OPTIONAL","OR","ORDER",
		"ORGANIZATION","OTHER","OTHERWISE","OUTPUT","OVER","OVERFLOW",
		"OVERLINE","OWNER",
		
		"PACKED-DECIMAL","PADDING","PAGE","PAGE-COUNTER","PARAGRAPH","PASSWORD",
		"PATH","PERFORM","PERSISTENT","PF","PH","PIC","PICTURE","PLUS","POINTER",
		"POS","POSITION","POSITIONING","POSITIVE","PR","PREFIXING","PRESENT",
		"PREVIOUS","PRINT","PRINT-SWITCH","PRINTER","PRINTER-1","PRINTING",
		"PRIOR","PROCEDURE","PROCEDURE-POINTER","PROCEDURES","PROCEED",
		"PROCESS","PROCESSING","PROGRAM","PROGRAM-ID","PROMPT",
		"PROPERTY","PROTECT","PROTECTED","PROTOTYPE","PURGE",
		
		"QUEUE","QUOTE","QUOTES",
		
		"RANDAM","RANGE","RD","RDB-COUNT","RDB-RDNODE","DRB-STATUS","READ",
		"READY","REALM","RECEIVE","RECEIVING","RECONNECT","RECORD",
		"RECORD-NAME","RECORD-OVERFLOW","RECORDING","RECORDS","RECURSIVE",
		"RED","REDEFINES","REEL","REFERENCE","REFERENCES","RELATION",
		"RELATIVE","RELEASE","RELOAD","REMAINDER","REMARKS","REMOVAL",
		"RENAMES","REORG-CRITERIA","REPEAT","REPEATED","REPLACE","REPLACING",
		"REPLY","REPORT","REPORTING","REPORTS","REPOSITORY","REQUIRED",
		"REREAD","RERUN","RESERVE","RESET","RESETTED","RETAINING","RETRIEVAL",
		"RETURN","RETURN-CODE","RETURNING","REVERSE","REVERSE-VIDEO",
		"REVERSED","REWIND","REWRITE","RF","RH","RIGHT","RIGHT-JUSTIFY",
		"ROLLBACK","ROUNDED","RULE","RUN",
		
		"SO1","SO2","SO3","SO4","SO5","SA","SAME","SCREEN","SD","SEARCH",
		"SEARCH","SECRET","SECTION","SECURE","SECURITY","SEEK","SEGMENT",
		"SEGMENT-LIMIT","SELECT","SELECTION","SELECTIVE","SELF","SEND",
		"SENTENCE","SEPARATE","SEQUENCE","SEQUENTIAL","SERVICE","SET",
		"SHARED","SHIFT-IN","SHIFT-OUT","SIGN","SIZE","SKIP1","SKIP2","SKIP3",
		"SKY-BLUE","SORT","SORT-CONTROL","SORT-CORE-SIZE","SORT-FILE-SIZE",
		"SORT-MERGE","SORT-SORT-MESSAGE","SORT-MODE-SIZE","SORT-OPTION",
		"SORT-RETURN","SOURCE","SOURCE-COMPUTER","SPACE","SPACE-FILL",
		"SPACES","SPECAIL-NAMES","SQL","SQUARE","SS","STANDARD","STANDARD-1",
		"STANDARD-2","START","STATUS","STATUS-0","STATUS-1","STATUS-2",
		"STATUS-3","STATUS-4","STATUS-5","STATUS-6","STATUS-7","STATUS-8",
		"STATUS-9","STATUS-10","STATUS-11","STATUS-12","STATUS-13","STATUS-14",
		"STATUS-15","STATUS-16","STOP","STOPPING","STORAGE","STORE","STRING",
		"STRUCTIRAL","STRUCTURE","SUB-QUEUE-1","SUB-QUEUE-2","SUB-QUEUE-3",
		"SUB-SCHEMA","SUBSCHEMA","SUBTRACT","SUFFIXING","SUM","SUPER",
		"SUPERVISOR","SUPPRESS","SUSPEND","SWITCHING","SYMBOLIC","SYNC",
		"SYNCHRONIZED","SNCHRONOUS","SYSIN","SYSIPT","SYSLST","SYSOUT","SYSPCH",
		"SYSPUNCH",
		
		"TAB","TABLE","TALLY","TALLYING","TAPE","TEMPORARY","TENANT","TERMINAL",
		"TERMINATE","TEST","TEXT","THAN","THEN","THROUGH","THRU","TIME",
		"TIME-OF-DAY","TIME-OUT","TIMEOUT","TIMES","TITLE","TO","TOP","TOTALED",
		"TOTALING","TRACE","TRACK-AREA","TRACK-LIMIT","TRACK","TRACKS",
		"TRAILING","TRAILING-SIGN","TRANSACTION","TRANSCEIVE","TRANSFER",
		"TRANSFORM","TRANSIENT","TRUE","TYPE",
		
		"UNDER","UNDERLINE","UNEQUAL","UNIT","UNIVERSAL","UNLOCK","UNPROTECTED",
		"UNSTRING","UNTIL","UP","UPDATE","UPON","UPPER","UPSI-0","UPSI-1",
		"UPSI-2","UPSI-3","UPSI-4","UPSI-5","UPSI-6","UPSI-7","USAGE",
		"USAGE-MDOE","USE","USER","USING",
		
		"VALID","VALIDATE","VALUE","VALUES","VARIABLE","VARIANT","VARYING",
		"VERTICAL","VIA",
		
		"WAIT","WAITING","WHEN","WHEN-COMPILED","WHERE","WHITE","WINDOW",
		"WINDOW-CURSOR","WINDOW-KEY","WINDOW-KEYCODE","WINDOW-STATUS",
		"WITH","WITHIN","WORDS","WORKING-STORAGE","WRITE","WRITE-ONLY",
		"WRITE-VERIFY","WS",
		
		"YELLOW",
		
		"ZERO","ZERO-FILL","ZEROES","ZERO"
	};
	
	private TokenKind(){}
}
